### PR TITLE
Release 3.3.0

### PR DESCRIPTION
**Pull request by Tieqiong**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tieqiong** [comment]
@conda-forge-admin, please rerender

**Comment by sbillinge** [comment]
@Tieqiong please check, I think we may need to change the python versions in the meta.yaml.

**Comment by Tieqiong** [comment]
@conda-forge-admin, please rerender

**Comment by Tieqiong** [comment]
@sbillinge For some reason the Azure pipeline check was not run, and I believe it's also happening for diffpy.utils. We might not be able to release to conda-forge before figuring this out...

**Comment by sbillinge** [comment]
Ah, o missed that in this case. Yes, let's not merge any more until we sort this out

**Comment by bobleesj** [comment]
Screenshot 2024-10-28 at 10 28 18 PM

 @Tieqiong @sbillinge  Just wanted to share our merged CI failed, hence 3.3.0 isn't available on conda-forge: https://anaconda.org/conda-forge/diffpy.structure/files

**Comment by Tieqiong** [comment]
@bobleesj where were you able to see the checks?

**Comment by bobleesj** [comment]
Screenshot 2024-10-28 at 10 33 59 PM

in the main repo

**Comment by Tieqiong** [comment]
@bobleesj It seems like nothing was actually run. they all stop at very early stage in a few seconds. Were you able to run Azure pipeline in other feedstocks PRs?

**Comment by bobleesj** [comment]
Oddly, yes https://github.com/conda-forge/diffpy.labpdfproc-feedstock - it does not have the permission problem like here. 

In diffpy.utils-feedstock, I've tagged admins for help.

**Comment by bobleesj** [comment]
@Tieqiong CI running again - `git commit --allow-empty -m "push empty, re-run CI"` worked

https://github.com/conda-forge/diffpy.utils-feedstock/pull/39

**Pull request merged**
