### PR TITLE
Release 3.2.3

### PR DESCRIPTION
**Pull request by Tieqiong**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tieqiong** [comment]
@conda-forge-admin, please rerender

**Comment by bobleesj** [comment]
I think the CI is failing since conda-forge I believe automatically uses 3.13 to setup Python (a few weeks ago), hence it became urgent for the group.

**Comment by sbillinge** [comment]
@Tieqiong maybe we don't want to push these releases all the way to conda-forge, but do the 3.13 migration and then push all the way to CF?

**Comment by Tieqiong** [comment]
@sbillinge yes there's no need for this version to be on conda forge. We can do a new release for python version bumping on pypi and skip this on conda forge.

> I think the CI is failing since conda-forge I believe automatically uses 3.13 to setup Python (a few weeks ago), hence it became urgent for the group.
> 
> But this means our new `requires-python` is working as intended.

@bobleesj I think this is because we have `python >=3.10` in meta.yml. It might be better to define the upper limit that aligns with our actual version.

**Comment by bobleesj** [comment]
Closing - 3.3.0 will be created instead

**Pull request closed without merging**
